Instant Address Standard/main/default/objects/Service_Maste_Transaction__c/Service_Maste_Transaction__c.object-meta.xml
<CustomObject>
    <label>Service_Maste_Transaction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Service_Maste_Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service_Maste_Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Instant Address Standard/main/default/objects/Service_Maste_Transaction__c/fields/Total_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Total_Addresses__c</fullName>
    <label>Total Addresses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Instant Address Standard/main/default/objects/Service_Maste_Transaction__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>TransactionId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Instant Address Standard/main/default/classes/FinishingBatch_CL.cls
public class FinishingBatch_CL {
    //Properties    
    public string TransactionId{set;get;}
    public PageSource source{set;get;}
    public Batch_SentDataBatchable baSendata{set;get;} 
    //Contructor
    public FinishingBatch_CL (){
        try{
            
            source= new PageSource();
           string tran = ApexPages.currentPage().getParameters().get('TransactionId'); 
        
             
            if(string.isNotEmpty(tran)){
               TransactionId = tran; //ApexPages.currentPage().getParameters().get('TransactionId');    
                SentNextBatch();
            }   
          
        }
        catch(Exception e){
            Batch_Helpers.LogError(e );
        }    
    }
    //Events
    public pageReference NextBatch(){
        try{
           return SentNextBatch();  
        }
        catch(exception e){
          Batch_Helpers.LogError(e); 
        } 
        return null;      
    }
   
    //Private  
      
    private pagereference SentNextBatch(){
       
       integer transcount = database.countQuery('SELECT COUNT() FROM Service_Maste_Transaction__c WHERE TransactionId__c = \''+TransactionId +'\' ');
        if(transcount == 0){
            
            return  new pagereference('/apex/Batch_NewSession_UI?finishmessage=true&total='+source.BatchTotalCount);
        }
        else{ 
            Service_Maste_Transaction__c  dt = [SELECT TransactionId__c,Data__c, Total_Addresses__c  FROM Service_Maste_Transaction__c WHERE TransactionId__c =:TransactionId LIMIT 1];
             baSendata = (Batch_SentDataBatchable)System.JSON.deserialize(dt.Data__c, Batch_SentDataBatchable.class); 
            
            
           source.BatchTotalCount  = baSendata.TotalBatchCount;   
            source.BatchTotalDownloaded= integer.valueOf(dt.Total_Addresses__c);     
            if(source.BatchTotalCount > 0) {
                source.BatchTotalDownloadedPrecentage = String.valueOf((integer)(source.BatchTotalDownloaded * 100 / source.BatchTotalCount));
            }
        }
        return null;
         
    }
    //Public 

    //Class
    public class PageSource{
        public string  TransactionId{get;set;}       
        public string  TransactionOverallStatus{get;set;}
        public integer BatchTotalDownloaded{get;set;}
        public integer BatchTotalCount{get;set;}
        public string  BatchTotalDownloadedPrecentage{get;set;}
    }
}